version: '3'
services:
  nginx: 
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    image: rkucherenko/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rkucherenko
      - MONGO_INITDB_ROOT_PASSWORD=pass123
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:6.2.1

volumes:
  mongo-db: {}
